### ISSUE TITLE
Not a working link "NativeScript"

### ISSUE THREAD

**Issue by ArtemZHR** [translation-gang/docs-next#21]
![image](https://user-images.githubusercontent.com/60423272/120484355-a89b9000-c3bb-11eb-996f-937a53a43aad.png)
![image](https://user-images.githubusercontent.com/60423272/120484399-b3eebb80-c3bb-11eb-962e-86974ea9f4e5.png)

**Comment by Alex-Sokolov** [comment]
Действительно. Видимо сайт обновили. Возможно стоит просто на главную оставить ссылку? Отдельный гайд для Vue найти у меня не получается. Ну и в оригинальной документации такая же неработающая ссылка. Так что у вас есть возможность отправить им PR и в русском переводе мы это изменение тоже отразим
