### ISSUE TITLE
Massive replace "Во Vue" to "В Vue"

### ISSUE THREAD

**Issue by WinterSilence** [translation-gang/docs-next#53]
Массовая замена "Во Vue" на "В Vue", а то звучит как-то странно.

**Comment by Alex-Sokolov** [comment]
Привет! С наступившим :)

Честно говоря не знаю. Изначально так везде писали, потому что читается приятнее "во вью" чем спотыкаясь "в вью". Но правила как с английскими словами тут сочетаться должно или нет я не нашёл. Если считаете что станет лучше, делайте PR :)
